### ISSUE TITLE
Not working atm

### ISSUE THREAD

**Issue by Terroosh** [IlliumIv/Tradie#1]
When you trade with someone Tradie displays images and amounts next to the trade window. So if someone is trading you 50 Chaos Orbs then next to the trade window you will see the chaos orb image and the text "50."
Thank you for trying to update it though, but it's not working atm. No images/text display.

Maybe GameController.Game.IngameState.UIRoot needs update for GetTradingWindow() and GetNpcTadeWindow()?

I have the images pack already located here: https://github.com/Macaddict42/Tradie/tree/master/images/Art/2DItems

**Comment by IlliumIv** [comment]
Ty a lot for for explaining to me what the plugin does.
I correctly understood that his only function is to calculate the amount of currency, and draw its icon and value?
I'll try to fix it completely, it does not look complicated.

**Comment by IlliumIv** [comment]
@Terroosh U can test [fixes](https://github.com/IlliumIv/Tradie/releases)?

**Comment by Terroosh** [comment]
> 
> 
> @Terroosh U can test [fixes](https://github.com/IlliumIv/Tradie/releases)?

It's sort of working. Getting a lot of [Error] Tradie: Sometime went wrong in GetItemObjects() for a brief moment
It's a bit wonky: https://puu.sh/Ep7C4/21b64517e1.png
Here the alchs don't show up: https://puu.sh/Ep7CH/ac3fa379f9.png
But then they do: https://puu.sh/Ep7Dr/cdd9049f33.png
And here's gems: https://puu.sh/Ep7GS/b995b17c20.png

It's really random.

**Comment by IlliumIv** [comment]
@Terroosh yep, i know about this problem. ExileApi sometimes provide wrong npc's items list. The problem don't depend on a specific item.
I tested plugin a bit time, but i think that problem is only when trading with npc.
Better solution atm - ignoring wrong items. I added check in last release - if items list is wrong, plugin will ignore items. Probably plugin will work even ExileApi will be updated to fixed this.

**Comment by Terroosh** [comment]
> 
> 
> @Terroosh yep, i know about this problem. ExileApi sometimes provide wrong npc's items list. The problem don't depend on a specific item.
> I tested plugin a bit time, but i think that problem is only when trading with npc.
> Better solution atm - ignoring wrong items. I added check in last release - if items list is wrong, plugin will ignore items. Probably plugin will work even ExileApi will be updated to fixed this.

That makes sense. Thanks for updating the addon. It makes trading a lot safer/easier.
