### ISSUE TITLE
3.9 Update

### ISSUE THREAD

**Issue by Terroosh** [IlliumIv/Tradie#2]
Hi, I think GameController.Game.IngameState.UIRoot.Children needs updating again for the trade windows.

**Comment by Terroosh** [comment]
Hi,

I think GetTradingWindow() is
`GameController.Game.IngameState.UIRoot.Children[1].Children[81].Children[3].Children[1].Children[0].Children[0];`

and GetNpcTadeWindow() is

`GameController.Game.IngameState.UIRoot.Children[1].Children[80].Children[3];`

**Comment by IlliumIv** [comment]
Done
